name: SAP CAP CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: empsaldetails

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install CDS DK
        run: npm install -g @sap/cds-dk

      - name: Build CAP Project
        run: cds build

      - name: Install MBT
        run: npm install -g mbt

      - name: Build MTAR
        run: mbt build
